
version: '2'

services:

  auth:
    container_name: auth
    build: .
    env_file:
     - .env
    volumes:
     - .:/var/www

  db:
    container_name: db
    image: registry.dcapi.net/dcpro/main/base/mysql
    env_file:
     - .env
