
version: '2'

services:

  users:
    container_name: users
    build: .
    env_file:
     - .env
    volumes:
     - .:/var/www

  db:
    container_name: db
    image: esblng/base/mysql
    env_file:
     - .env
