version: '3.3'
services:

  db:
    container_name: db
    image: esblng/base/mysql
    environment:
     - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
     - 127.0.0.1:3322:3306

  clickhouse:
    container_name: clickhouse
    image: yandex/clickhouse-server:18.14.11