
version: '2'

services:
  api:
    container_name: api
    build: .
    env_file:
      - .env
    volumes:
      - .:/var/www

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq
    env_file:
     - .env